### ISSUE TITLE
create project and user model

### ISSUE THREAD

**Issue by rwilcox** [WilcoxDevelopmentSolutions/odyssey#1]
Either do rails scaffold / do it manually, OR put the rails scaffold command you WOULD run as a comment into this ticket and I'll approve or not

**Comment by jcarvin** [comment]
Here's what I'm thinking: 

## User Model
`rails g scaffold user username:string first_name:string last_name:string email:string company:string title:string`

|pk|username|first_name|last_name|email|company|title|team|
|---|----------|-------------|----------|------|---------|------|---|
|1|jdoe|john|doe|jdoe@gmail.com|foobar inc.|supervisor|N/A|
|2|bsmith|ben|smith|bsmith@gmail.com|foobar inc.|developer|1234|

## Project Model

### Stories

`rails g scaffold story in_order_to:text as:string i_want_to:text i_do:text this_happens:text importance:int comments:text dev_comments:text difficulty:int epic:int user:int dev_team:int`

|in_order_to|as|i_want_to|i_do|this_happens|importance|comments|dev_comments|difficulty|epic|user|dev_team|
|----------|-------------|----------|------|---------|------|-----|-----|-----|-----|-----|-----|
|Create a new user story|a supervisor|be able to click a button and input some data|When I click the button to create a new user story|Text boxes should appear for me to enter my thoughts/ideas|3|There should also be a way to assign user stories to individual developers/developer teams as well as a way for them to comment and respond|`foo bar`|1|{this would be an integer relating to an epic if applicable.}|1 {int relating to user who is requesting feature}|1234{int relating to dev or dev team}|

### Other Thoughts

Would it be necessary to have another table for epics or for dev teams? Or do you think that would be excessive?

**Comment by rwilcox** [comment]
User model:

  - [ ] company's not a bad idea, but... eh, let's remove it for now, and come back to it later with an association if it's useful
  - [ ] let's remove title, we'll replace it with a role enum field and maybe do something with permissions based on that later.

Story model:

  - [ ] I would call user more explicitly as "author"
  - [ ] add a `story_kind:int` instead of `epic`. That way we can have stories, epics, and kinds of stories we haven't thought of yet.

We will need another table for teams. At some very near point in the future we need some kind of table to let stories have other stories that are children of it (ie that's how we see all the stories in an epic). But not for today.

**Comment by jcarvin** [comment]
Let me know how this looks. If you're happy with it, I'll run them and submit a PR

---


#### Changes
##### user
`rails g scaffold user username:string first_name:string last_name:string email:string role:enum`
* `title:int` to `role:enum`
* removed `company:string`

##### story
`rails g scaffold story in_order_to:text as:string i_want_to:text i_do:text this_happens:text importance:int comments:text dev_comments:text difficulty:int story_kind:int author:int`
* `user:int` to `author:int`
* added `story_kind:int`

**Comment by rwilcox** [comment]
If you're into enums use it for story kind too. And maybe importance .

(Not diifucukity I like the ability for that to go super up)

**Comment by jcarvin** [comment]
Gotcha! How about:

##### user
`rails g scaffold user username:string first_name:string last_name:string email:string role:enum`

##### story
`rails g scaffold story in_order_to:text as:string i_want_to:text i_do:text this_happens:text importance:enum comments:text dev_comments:text difficulty:int story_kind:enum author:int`

**Comment by rwilcox** [comment]
Ship it!

I wouldn't be surprised if the command gave you errors, however. You may need to set those types as integers in your command, then go into the models and manually use an enum declaration.

http://edgeapi.rubyonrails.org/classes/ActiveRecord/Enum.html

**Comment by rwilcox** [comment]
Closed in PR #14 (although it implemented User and Story... which I didn't really catch until now. Regardless, both of these needed to be done!
