### ISSUE TITLE
Project model

### ISSUE THREAD

**Issue by rwilcox** [WilcoxDevelopmentSolutions/odyssey#16]
Create a Project model:

  * name
  * author_id
  * has_many :stories
  * has_many :team_members
  * has_many :users, through: :team_members

  def current_team_members
    self.team_members.current
  end

Create a Team Members model:
 * belongs_to :user
  * belongs_to :project
  * state: enum (pending, current, disavowed)

Changes to existing functionality:

  * add new Project association to Story model: add `belongs_to` association + required database field
  * Add Project popup to Story form partial.
  * On new Story, save currently selected Project (ID) into the Rails session.
  * The Project popup should default to be (the Project ID you stored in the session) <-- in user story form: "As a story writer I want the story form to default to the last Project I selected, so that I write stories more efficiently"

**Comment by jcarvin** [comment]
c4bdb5b07ab0a77bea30712789ac5bdead615534 should address _some_ of this. Namely the models themselves. Let me know if you would like anything changed within these models.

On the subject of changes to the existing functionality:
* should Story `belongs_to :project`?
* Can you expand a little more on the Project popup? I'm unsure of what you mean.

**Comment by rwilcox** [comment]
Some notes:

  * You forgot project `belongs_to :author, class: User`. You have the field in the migration, just missed that part
  * Probably Project#current_team_members is one of those things that need an actual test. Add FactoryGirl models for User, Team Member and Project. Make a test that populates team members for a project, setting some of them to active, some of them to disavowed and some of them to invited. Then you should only get the invited ones back.

Theoretically this could be three separate tests, as we have three different behaviors in the app:

  * Project#current_team_members should show active team members
  * Project#current_team_members should not show invited team members
  * Project#current_team_members should not show disavowed team members.

(So maybe do all the setup in an rspec `before` block, then your `it` statements can just do simple tests?

Ok, back to your questions:

> should Story belongs_to :project?

Please. Make a migration that adds this fields to Story, add a `belongs_to` association to Story and a `has_many` association to Project.

> Can you expand a little more on the Project popup? I'm unsure of what you mean.

So you'll need to manually add a field to `app/views/stories/_form.html.erb`, so we can populate what project a story goes with. There's a helper in Rails that puts together this popup, [collection_select](https://apidock.com/rails/ActionView/Helpers/FormOptionsHelper/collection_select) that does most of the super annoying bits for you.

Does this help?

(You also may need to add `project_id` to the `story_params` function in StoriesController...)

 and manually add that field into the form for Story. (and remember the "remember last setting" feature I wanted, above :) )

**Comment by rwilcox** [comment]
(But I'm excited: once we have these three major parts together we can work on how a user actually goes through and *does* these things!!!)

**Comment by jcarvin** [comment]
Alright! So I ran `rails g migration AddProjectToStory project:belongs_to` and that did a lot of work for me. I think it covered all of the bases.

I also added `belongs_to :author, class_name: User` to project.rb

and added `:project_id` to `story_params`

---
Honestly I'm not totally sure how to add the FactoryGirl models and tests yet. I'll explore that asap.

**Comment by rwilcox** [comment]
If you want to learn from example I could do one for you. Let me know.

**Comment by jcarvin** [comment]
If you wouldn't mind, that would be great! Thank you!

**Comment by rwilcox** [comment]
Fixedin PR #18
